{
 "title": "node-postgres",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(pg_pool_connections_created_total,instance)"
    }
   },
   { "name": "host", "label": "Host", "query": { "query": "label_values(pg_pool_max,host)" } },
   {
    "name": "database",
    "label": "Database",
    "query": {
     "query": "label_values(pg_pool_max,database)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Client", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Disconnected Connections",
   "type": "timeseries",
   "description": "The total number of disconnected connections.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(pg_client_disconnects_total{instance=~\"$instance\", host=~\"$host\", database=~\"$database\"}) by (instance, host, database)",
     "legendFormat": "{{instance}} - {{host}} - {{database}}"
    }
   ]
  },
  {
   "title": "Disconnected Connections Rate",
   "type": "timeseries",
   "description": "The total number of disconnected connections.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(rate(pg_client_disconnects_total{instance=~\"$instance\", host=~\"$host\", database=~\"$database\"}[$__rate_interval])) by (instance, host, database)",
     "legendFormat": "{{instance}} - {{host}} - {{database}}"
    }
   ]
  },
  {
   "title": "Connection Errors",
   "type": "timeseries",
   "description": "The total number of connection errors with a database.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(pg_client_errors_total{instance=~\"$instance\", host=~\"$host\", database=~\"$database\"}) by (instance, host, database)",
     "legendFormat": "{{instance}} - {{host}} - {{database}}"
    }
   ]
  },
  {
   "title": "Connection Errors",
   "type": "timeseries",
   "description": "The total number of connection errors with a database.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(rate(pg_client_errors_total{instance=~\"$instance\", host=~\"$host\", database=~\"$database\"}[$__rate_interval])) by (instance, host, database)",
     "legendFormat": "{{instance}} - {{host}} - {{database}}"
    }
   ]
  },
  { "title": "Pool", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Active Connections",
   "type": "timeseries",
   "description": "The number of connections that are currently in use.",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(irate(pg_pool_active_connections{instance=~\"$instance\", host=~\"$host\", database=~\"$database\"}[$__rate_interval])) by (instance, host, database)",
     "legendFormat": "{{instance}} - {{host}} - {{database}}"
    }
   ]
  },
  {
   "title": "Connection Pool Usage",
   "type": "timeseries",
   "description": "Current size of the connection pool, including idle and and in-use members.",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(pg_pool_size{instance=~\"$instance\", host=~\"$host\", database=~\"$database\"}) by (instance, host, database)",
     "legendFormat": "{{instance}} - {{host}} - {{database}}"
    }
   ]
  },
  {
   "title": "Connection Pool Utilization",
   "type": "timeseries",
   "description": "Current size of the connection pool, including idle and and in-use members.",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(pg_pool_size{instance=~\"$instance\", host=~\"$host\", database=~\"$database\"}) by (instance, host, database) / sum(pg_pool_max{instance=~\"$instance\", host=~\"$host\", database=~\"$database\"}) by (instance, host, database)",
     "legendFormat": "{{instance}} - {{host}} - {{database}}"
    }
   ]
  },
  {
   "title": "Waiting Connections",
   "type": "timeseries",
   "description": "The total number of waiting connections.",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(pg_pool_waiting_connections{instance=~\"$instance\", host=~\"$host\", database=~\"$database\"}) by (instance, host, database)",
     "legendFormat": "{{instance}} - {{host}} - {{database}}"
    }
   ]
  },
  {
   "title": "Idle Connections",
   "type": "timeseries",
   "description": "The total number of idle connections.",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(pg_pool_idle_connections{instance=~\"$instance\", host=~\"$host\", database=~\"$database\"}) by (instance, host, database)",
     "legendFormat": "{{instance}} - {{host}} - {{database}}"
    }
   ]
  },
  {
   "title": "Connection Pool Max",
   "type": "timeseries",
   "description": "The maximum size of the connection pool.",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(pg_pool_max{instance=~\"$instance\", host=~\"$host\", database=~\"$database\"}) by (instance, host, database)",
     "legendFormat": "{{instance}} - {{host}} - {{database}}"
    }
   ]
  },
  {
   "title": "Removed Connections Rate",
   "type": "timeseries",
   "description": "The total number of removed connections.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(rate(pg_pool_connections_removed_total{instance=~\"$instance\", host=~\"$host\", database=~\"$database\"}[$__rate_interval])) by (instance, host, database)",
     "legendFormat": "{{instance}} - {{host}} - {{database}}"
    }
   ]
  },
  {
   "title": "Removed Connections",
   "type": "timeseries",
   "description": "The total number of removed connections.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(pg_pool_connections_removed_total{instance=~\"$instance\", host=~\"$host\", database=~\"$database\"}) by (instance, host, database)",
     "legendFormat": "{{instance}} - {{host}} - {{database}}"
    }
   ]
  },
  {
   "title": "Connection Errors",
   "type": "timeseries",
   "description": "The total number of connection errors with a database.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(pg_pool_errors_total{instance=~\"$instance\", host=~\"$host\", database=~\"$database\"}) by (instance, host, database)",
     "legendFormat": "{{instance}} - {{host}} - {{database}}"
    }
   ]
  },
  {
   "title": "Connection Errors Rate",
   "type": "timeseries",
   "description": "The total number of connection errors with a database.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(rate(pg_pool_errors_total{instance=~\"$instance\", host=~\"$host\", database=~\"$database\"}[$__rate_interval])) by (instance, host, database)",
     "legendFormat": "{{instance}} - {{host}} - {{database}}"
    }
   ]
  }
 ]
}