name: 'Continuous Integration'
on:
  push:
    branches:
      - 'main'
    paths-ignore:
      - '**.md'
  pull_request:
    branches:
      - 'main'

permissions:
  contents: read

jobs:
  ci:
    strategy:
      matrix:
        node-version: ['18.x', '20.x', '21.x']
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - run: npm run ci