name: Coveralls
on:
  push:
    branches:
      - 'main'
    paths:
      - '**.ts'

permissions:
  contents: read

jobs:
  coveralls:
    uses: christiangalsterer/github-actions/.github/workflows/node_coveralls.yaml@main
