name: Coveralls
on:
  push:
    branches:
      - 'main'
    paths-ignore:
      - '**.md'
  pull_request:
    branches:
      - 'main'

permissions:
  contents: read

jobs:
  ci:
    uses:
      christiangalsterer/github-actions/.github/workflows/node_coveralls.yaml@main