name: Release
on:
  push:
    branches:
      - 'main'

permissions:
  contents: write
  pull-requests: write

jobs:
  release:
    uses:
      christiangalsterer/github-actions/.github/workflows/node_release.yaml@main
    secrets: inherit  